# Generated by Django 5.0.1 on 2024-01-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
