# Generated by Django 5.0.1 on 2024-01-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_recipes_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', models.CharField(default='none', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='photos/blog/%y/%m/%d')),
                ('added_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipes',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
