# Generated by Django 5.0.1 on 2024-01-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_blogrecipes_alter_recipes_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipes',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
