# Generated by Django 5.0.1 on 2024-01-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_alter_blogrecipes_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipes',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
