# Generated by Django 5.0.1 on 2024-01-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_blogrecipes_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipes',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='country',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='details',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
