# Generated by Django 5.0.1 on 2024-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_alter_blogrecipes_active_alter_blogrecipes_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipes',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
