# Generated by Django 5.0.1 on 2024-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_blogrecipes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecipes',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='country',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogrecipes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
