# Generated by Django 5.0.1 on 2024-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_blogrecipes_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipes',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
