# Generated by Django 5.0.1 on 2024-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='populat',
            field=models.BooleanField(null=True),
        ),
    ]
