# Generated by Django 5.0.1 on 2024-02-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_recipes_populat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='populat',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
