# Generated by Django 5.0.1 on 2024-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_rename_populat_recipes_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes_opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('recipe_id', models.CharField(max_length=11)),
                ('recipe_name', models.CharField(max_length=250)),
            ],
        ),
    ]
