# Generated by Django 5.0.1 on 2024-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0019_recipes_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes_opinion',
            name='message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
