# Generated by Django 5.0.1 on 2024-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0020_recipes_opinion_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes_opinion',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='recipes_opinion',
            old_name='message',
            new_name='opinion',
        ),
        migrations.RenameField(
            model_name='recipes_opinion',
            old_name='recipe_id',
            new_name='recipeId',
        ),
        migrations.RenameField(
            model_name='recipes_opinion',
            old_name='recipe_name',
            new_name='recipeName',
        ),
        migrations.RenameField(
            model_name='recipes_opinion',
            old_name='user_name',
            new_name='user',
        ),
    ]
