# Generated by Django 5.0.1 on 2024-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0021_rename_user_email_recipes_opinion_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes_opinion',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipes_opinion',
            name='recipeId',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='recipes_opinion',
            name='recipeName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recipes_opinion',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
