# Generated by Django 5.0.1 on 2024-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0023_alter_contact_us_email_alter_contact_us_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes_opinion',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
